global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'debug'
  email_configs:
  - to: 'EMAIL@gmail.com'
    from: 'EMAIL@gmail.com'
    smarthost: 'sandbox.smtp.mailtrap.io:587'
    smp_from: 'alersts@examples.com'
    auth_username: '1eb4153233f2e3'
    auth_identity: 'EMAIL@gmail.com'
    auth_password: '3846a7e57fc316'
